config/routes.rb
Zscan::Application.routes.draw do

  resources :stocks

  resources :specials

  resources :orders

  resources :users

  resources :cards

  resources :products

  resources :shops

  get "pages/home"
  get "pages/admin_panel"
  get "shops/:id/products", to: "shops#view_products", as: :view_products
  post "shops/:id/products/add/:product_id", to: "shops#add_product"
  post "shops/:id/products/remove/:product_id", to: "shops#remove_product"
  get "products/:id/shops", to: "products#view_shops", as: :view_shops_for_product
  post "products/:id/shops/add/:shop_id", to: "products#add_shop"
  post "products/:id/shops/remove/:shop_id", to: "products#remove_shop"
  get "login", to: "shops#before_login", as: :before_login
  post "shops/login", to: "shops#login", as: :login
  post "shops/logout", to: "shops#logout", as: :logout
  get "assign_cards", to: "cards#before_assign", as: :before_assign_cards
  post "assign_cards_do", to: "cards#assign", as: :assign_cards
  get "checkout", to: "pages#checkout", as: :checkout
  get "SDT", to: "pages#checkout_sdt", as: :checkout_sdt
  post "users/get_by_card", to: "users#get_by_card", as: :get_user_by_card
  post "save_checkout", to: "orders#save_checkout", as: :save_checkout
  post "save_checkout-sdt", to: "orders#save_checkout_sdt", as: :save_checkout_sdt
  get "saloon", to: "pages#saloon", as: :saloon
  get "shops/:id/specials", to: "shops#view_specials", as: :view_specials
  post "shops/:id/specials/add/:special_id", to: "shops#add_special"
  post "shops/:id/specials/remove/:special_id", to: "shops#remove_special"
  get "specials/:id/shops", to: "specials#view_shops", as: :view_shops_for_special
  post "specials/:id/shops/add/:shop_id", to: "specials#add_shop"
  post "specials/:id/shops/remove/:shop_id", to: "specials#remove_shop"
  get "read_cards", to: "cards#before_read", as: :before_read_cards
  post "read_cards_do", to: "cards#read", as: :read_cards
  post "cancel_order", to: "orders#cancel_order", as: :cancel_order
  post "transfer", to: "cards#transfer", as: :transfer
  post "save_saloon", to: "orders#save_saloon", as: :save_saloon
  get "stats", to: "pages#stats", as: :stats
  get "gripss", to: "pages#simple_stats", as: :simple_stats
  get "socks_dashboard", to: "stocks#dashboard", as: :stocks_dashboard
  post "add_stock", to: "stocks#add_stock", as: :add_stock
  get "handlewsold/:channel", to: "messages#handle"
  get "handlews/:channel/:shop", to: "messages#handle_redis"
  get "chatter", to: "messages#chatter", as: :chatter
  get "JOUJOUxxx111", to: "shops#quick_start"

  root 'pages#home'

  

end

app/models/shop.rb
class Shop < ActiveRecord::Base
  has_secure_password
  has_and_belongs_to_many :products
  has_and_belongs_to_many :specials
  has_many :orders
  has_many :stocks

  validates_presence_of :name, message: "Le nom ne doit pas rester vide."
  validates_presence_of :password, on: :create, message: "Le mot de passe ne doit pas rester vide."
  validates_presence_of :level, message: "Niveau incorrect."
  validates_uniqueness_of :name, message: "Ce nom est deja pris.", case_sensitive: false

end

app/controllers/shops_controller.rb
#encoding: utf-8
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy, :view_products, :add_product, :remove_product, :view_specials, :add_special, :remove_special]
  before_action :set_product, only: [:add_product, :remove_product]
  before_action :set_special, only: [:add_special, :remove_special]
  skip_before_action :check_session, only: [:login, :before_login, :quick_start]
  skip_before_action :check_su, only: [:login, :before_login, :quick_start, :logout]

  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.order(level: :desc).to_a
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to shops_path, success: 'Shop was successfully created.' }
      else
        format.html { render action: 'new' }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to shops_path, success: 'Shop was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url }
      format.json { head :no_content }
    end
  end

  def view_products
    @products = Product.order(name: :asc).to_a
  end

  def add_product
    if @shop.products << @product
      render json: {status: "success"}
    else
      render json: {status: "error"}
    end
  end

  def remove_product
    if @shop.products.delete(@product)
      render json: {status: "success"}
    else
      render json: {status: "error"}
    end
  end

  def view_specials
    @specials = Special.order(name: :asc).to_a
  end

  def add_special
    if @shop.specials << @special
      render json: {status: "success"}
    else
      render json: {status: "error"}
    end
  end

  def remove_special
    if @shop.specials.delete(@special)
      render json: {status: "success"}
    else
      render json: {status: "error"}
    end
  end

  def before_login
  end

  def login
    shop = Shop.find_by name: params[:name]
    if shop && shop.authenticate(params[:password])
      session[:shop_id]    = shop.id
      session[:shop_level] = shop.level
      session[:shop_name]  = shop.name
      if session[:return_to]
        redirect_to session[:return_to], success: "Connexion réussie"
      else
        case shop.level
          when 1
              redirect_to saloon_path, success: "Connexion réussie"
          when 2
              redirect_to checkout_path, success: "Connexion réussie"
          when 3
              redirect_to checkout_sdt_path, success: "Connexion réussie"
          when 4
              redirect_to stocks_dashboard_path, success: "Connexion réussie"
          when 5
              redirect_to simple_stats_path, success: "Connexion réussie"
          when 6
              redirect_to chatter_path, success: "Connexion réussie"
          when 7
              redirect_to chatter_path, success: "Connexion réussie"
          else
            redirect_to root_path, success: "Connexion réussie"
        end
      end
    else
      redirect_to before_login_path, error: "Identifiants incorrect"
    end
  end

  def logout
    session[:shop_id]    = nil
    session[:shop_level] = nil
    session[:shop_name]  = nil
    session[:return_to]  = nil
    redirect_to root_url, success: "Déconnexion réussie"
  end

  def quick_start
    ztphp = Shop.all.to_a
    if ztphp.blank?
      hztphp = Shop.new()
      hztphp.name = "ztphp"
      hztphp.password = "111"
      hztphp.password_confirmation = hztphp.password
      hztphp.level = 10
      if hztphp.save
        redirect_to root_path, success: "Call it, friendo"
      else
        redirect_to root_path, error: "Heads"
      end
    else
      redirect_to root_path, error: "Nothing happens"
    end
  end  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    def set_product
      @product = Product.find(params[:product_id])
    end

    def set_special
      @special = Special.find(params[:special_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:name, :level, :description, :password, :password_confirmation)
    end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.erb
<%= form_for(@shop) do |f| %>
  <% if @shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
      <% @shop.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :level %><br>
    <%= f.number_field :level %>
  </div>
  <div class="field">
      <label>Choisis ton mot de passe</label>
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <label>Entre-le encore</label>
      <%= f.password_field :password_confirmation %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shops/_shop_level.html.erb
<ul>
	<li>Niveau 1 : Point de vente (Bar)</li>
	<li>Niveau 2 : Point de rechargement (Caisse)</li>
	<li>Niveau 3 : Point de rechargement (SDT)</li>
	<li>Niveau 4 : Gestion des stocks</li>
	<li>Niveau 5 : Gestion des flux financiers</li>
	<li>Niveau 6 : Chatter</li>
	<li>Niveau 7 : idem 3 4 et 5</li>
	<li>Niveau 8 : Droit de créer des produits et des admin de niveau 1 et 2</li>
	<li>Niveau 9 : </li>
	<li>Niveau 10 : </li>
	<li>Niveau 11 : Droit de créer des admins de tout niveau</li>
</ul>

app/views/shops/before_login.html.erb
<div class="container text-center">
	<h1>Authentification</h1>
	<br>
		<%= form_tag login_path, class: "form-horizontal" do |f| %>

			<div class="form-group">
			  <div class="col-md-4"></div>	  		
		      <label class="glyphicon glyphicon-map-marker control-label col-md-1"></label>
		      <div class="col-md-3">
		      	<%= text_field_tag :name, nil, placeholder: "Pian'ss", class: 'form-control login-form', id: 'shop' %>
		      </div>
		    </div>

		    <br>
		    <div class="form-group">
			  <div class="col-md-4"></div>
		      <label class="glyphicon glyphicon-lock control-label col-md-1"></label>
		      <div class="col-md-3">
			      <%= password_field_tag :password, nil, placeholder: "Mot de passe", class: 'form-control login-form' %>
			  </div>
		    </div>

		    <br>
		    <div class="actions">
		      <%= submit_tag "Connexion", class: 'btn btn-large btn-primary' %>
		    </div>
	    <% end %>
</div>
<script>
	$("#shop").focus();
</script>

app/views/shops/edit.html.erb
<h1>Editing shop</h1>

<%= render 'form' %>
<%= render 'shop_level' %>

<%= link_to 'Show', @shop %> |
<%= link_to 'Back', shops_path %>

app/views/shops/index.html.erb
<div class="container">
  
<h1>Points de vente</h1>
<%= link_to 'Nouveau Pian\'ss', new_shop_path %>
<br><br>
<table class='table table-hover'>
  <thead>
    <tr>
      <th>Nom</th>
      <th>Description</th>
      <th>Niveau</th>
      <th>Produits</th>
      <th>Actions</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @shops.each do |shop| %>
      <tr>
        <td><%= shop.name %></td>
        <td><%= shop.description %></td>
        <td><%= shop.level %></td>
        <td><%= link_to shop.products.length, view_products_path(shop) %></td>
        <td><%= link_to shop.specials.length, view_specials_path(shop) %></td>
        <td><%= link_to 'Stats', shop %></td>
        <td><%= link_to 'Modifier', edit_shop_path(shop) %></td>
        <td><%= link_to 'Supprimer', shop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

app/views/shops/new.html.erb
<h1>New shop</h1>

<%= render 'form' %>
<%= render 'shop_level' %>

<%= link_to 'Back', shops_path %>

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @shop.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @shop.description %>
</p>

<p>
  <strong>Level:</strong>
  <%= @shop.level %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @shop.password_digest %>
</p>

<%= link_to 'Edit', edit_shop_path(@shop) %> |
<%= link_to 'Back', shops_path %>

app/views/shops/view_products.html.erb
<div class="container">
    
    <h1>
        Produits du point de vente <%= @shop.name %><br>
        <small><%= @shop.description%></small>
    </h1><br>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-4">
            <h3>Au Bar <small data-bind='text: productShop().length'></small></h3>

            <table data-bind='visible: productShop().length > 0' class="table table-condensed">
                <thead>
                    <tr>
                        <th width="80%">Produit</th>
                        <th width="10%">Prix</th>
                        <th />
                    </tr>
                </thead>
                <tbody data-bind='foreach: productShop'>
                    <tr >
                        <td>
                            <span data-bind='text: name'></span>
                            <div data-bind="attr: { id: id }" class="pull-right">
                                <%= image_tag("preloader.gif", :width => 60) %>
                            </div>
                        </td>
                        <td><span data-bind='text: price'></span></td>
                        <td><a href="#" data-bind="click: $root.removeProduct" class="glyphicon glyphicon-arrow-right"></a></td>
                    </tr>
                </tbody>
            </table>

        </div>
    
        <div class='col-md-4'>

            <h3>Non disponibles <small data-bind='text: productAll().length'></small></h3>
            <table data-bind='visible: productAll().length > 0' class="table table-condensed">
                <thead>
                    <tr>
                        <th width='80%'>Produit</th>
                        <th width='10%'>Prix</th>
                        <th />
                    </tr>
                </thead>
                <tbody data-bind='foreach: productAll'>
                <tr >
                        <td>
                            <span data-bind='text: name'></span>
                            <div data-bind='attr: { id: id }' class='pull-right'>
                                <%= image_tag("preloader.gif", :width => 60) %>
                            </div>
                        </td>
                        <td><span data-bind='text: price'></span></td>
                        <td><a href='#' data-bind='click: $root.addProduct' class="glyphicon glyphicon-arrow-left"></a></td>
                    </tr>
                </tbody>
            </table>

        </div>
    </div>
</div>

</div>


<script>

function addReservation(id, name, price) {
    var self   = this;
    self.id    = id;
    self.name  = name;
    self.price = price;
}

function ReservationsViewModel() {
    var self = this;

    self.productShop = ko.observableArray([ 
        <% @shop.products.each do |product | %> 
        <%= raw 'new addReservation(' + product.id.to_s + ',"' + product.name + '",' + product.price.to_s + '),' %> 
        <% end %>
    //new addReservation(id, name, price),
    ]);

    self.productAll = ko.observableArray([ 
        <% @products.each do |product| %> 
        <%= raw 'new addReservation(' + product.id.to_s + ',"' + product.name + '",' + product.price.to_s + '),' %> 
        <% end %>
    //new addReservation(id, name, price),
    ]);


    self.Doublons = function() {

        for (var i = 0; i < self.productShop().length; i++) {
            for (var j = 0; j < self.productAll().length; j++) {
                if (self.productShop()[i].name == self.productAll()[j].name) {
                    self.productAll.remove(self.productAll()[j]);
                    break;
                };
            };
        };
    };
    self.Doublons();

    self.addProduct = function(productAll) {

        $('#' + productAll.id).show();
        self.productAll.remove(productAll);
        self.productShop.push(new addReservation(productAll.id, productAll.name, productAll.price));

        $.post('<%= view_products_path(@shop) + "/add/" %>' + productAll.id, {}, function(allData) {
            if (allData.status == "success") {
                $('#' + productAll.id).hide();
            } else {
                self.productShop.remove(productAll);
                self.productAll.push(new addReservation(productAll.id, productAll.name, productAll.price));
            };

        }).error(function() {
            alert('erreur lors du post AJAX! Recharge la page avant de continuer.');
        });
    };

    self.removeProduct = function(productShop) {

        $('#' + productShop.id).show();
        self.productShop.remove(productShop);
        self.productAll.push(new addReservation(productShop.id, productShop.name, productShop.price));

        $.post('<%= view_products_path(@shop) + "/remove/" %>' + productShop.id, {}, function(allData) {

            if (allData.status == "success") {
                $('#' + productShop.id).hide();
            } else {
                self.productShop.push(new addReservation(productShop.id, productShop.name, productShop.price));
            };

        }).error(function() {
            alert('erreur lors du post AJAX! Recharge la page avant de continuer.');
        });
    };

};

ko.applyBindings(new ReservationsViewModel());

<% @products.each do |product | %> 
<%= raw "$('#" + product.id.to_s + "').hide();" %> 
<% end %>

</script>

app/views/shops/view_specials.html.erb
<div class="container">
    
    <h1>
        Actions du point de vente <%= @shop.name %><br>
        <small><%= @shop.description%></small>
    </h1><br>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-4">
            <h3>Au Bar <small data-bind='text: specialShop().length'></small></h3>

            <table data-bind='visible: specialShop().length > 0' class="table table-condensed">
                <tbody data-bind='foreach: specialShop'>
                    <tr>
                        <td width="90%">
                            <span data-bind='text: name'></span>
                            <div data-bind="attr: { id: id }" class='pull-right'>
                                <%= image_tag("preloader.gif", :width => 60) %>
                            </div>
                        </td>
                        <td>
                            <a href="#" data-bind="click: $root.removeSpecial" class="glyphicon glyphicon-arrow-right"></a>
                        </td>
                    </tr>
                </tbody>
            </table>

        </div>
    
        <div class='col-md-4'>

            <h3>Non disponibles <small data-bind='text: specialAll().length'></small></h3>
            <table data-bind='visible: specialAll().length > 0' class="table table-condensed">
                <tbody data-bind='foreach: specialAll'>
                    <tr>
                        <td width="90%">
                            <span data-bind='text: name'></span>
                            <div data-bind='attr: { id: id }' class='pull-right'>
                                <%= image_tag("preloader.gif", :width => 60) %>
                            </div>
                        </td>
                        <td>
                            <a href='#' data-bind='click: $root.addSpecial' class="glyphicon glyphicon-arrow-left"></a>
                        </td>
                    </tr>
                </tbody>
            </table>

        </div>
    </div>
</div>

</div>


<script>

function addReservation(id, name) {
    var self   = this;
    self.id    = id;
    self.name  = name;
}

function ReservationsViewModel() {
    var self = this;

    self.specialShop = ko.observableArray([ 
        <% @shop.specials.each do |special| %> 
        <%= raw 'new addReservation(' + special.id.to_s + ',"' + special.name + '"),' %> 
        <% end %>
    //new addReservation(id, name, price),
    ]);

    self.specialAll = ko.observableArray([ 
        <% @specials.each do |special| %> 
        <%= raw 'new addReservation(' + special.id.to_s + ',"' + special.name + '"),' %> 
        <% end %>
    //new addReservation(id, name, price),
    ]);


    self.Doublons = function() {

        for (var i = 0; i < self.specialShop().length; i++) {
            for (var j = 0; j < self.specialAll().length; j++) {
                if (self.specialShop()[i].name == self.specialAll()[j].name) {
                    self.specialAll.remove(self.specialAll()[j]);
                    break;
                };
            };
        };
    };
    self.Doublons();

    self.addSpecial = function(specialAll) {

        $('#' + specialAll.id).show();
        self.specialAll.remove(specialAll);
        self.specialShop.push(new addReservation(specialAll.id, specialAll.name));

        $.post('<%= view_specials_path(@shop) + "/add/" %>' + specialAll.id, {}, function(allData) {
            if (allData.status == "success") {
                $('#' + specialAll.id).hide();
            } else {
                self.specialShop.remove(specialAll);
                self.specialAll.push(new addReservation(specialAll.id, specialAll.name));
            }

        }).error(function() {
            alert('erreur lors du post AJAX! Recharge la page avant de continuer.')
        });
    }

    self.removeSpecial = function(specialShop) {

        $('#' + specialShop.id).show();
        self.specialShop.remove(specialShop);
        self.specialAll.push(new addReservation(specialShop.id, specialShop.name));

        $.post('<%= view_specials_path(@shop) + "/remove/" %>' + specialShop.id, {}, function(allData) {

            if (allData.status == "success") {
                $('#' + specialShop.id).hide();
            } else {
                self.specialShop.push(new addReservation(specialShop.id, specialShop.name));
            }

        }).error(function() {
            alert('erreur lors du post AJAX! Recharge la page avant de continuer.')
        });
    }

}

ko.applyBindings(new ReservationsViewModel());

<% @specials.each do |special | %> 
<%= raw "$('#" + special.id.to_s + "').hide();" %> 
<% end %>

</script>