config/routes.rb
Zscan::Application.routes.draw do

  resources :stocks

  resources :specials

  resources :orders

  resources :users

  resources :cards

  resources :products

  resources :shops

  get "pages/home"
  get "pages/admin_panel"
  get "shops/:id/products", to: "shops#view_products", as: :view_products
  post "shops/:id/products/add/:product_id", to: "shops#add_product"
  post "shops/:id/products/remove/:product_id", to: "shops#remove_product"
  get "products/:id/shops", to: "products#view_shops", as: :view_shops_for_product
  post "products/:id/shops/add/:shop_id", to: "products#add_shop"
  post "products/:id/shops/remove/:shop_id", to: "products#remove_shop"
  get "login", to: "shops#before_login", as: :before_login
  post "shops/login", to: "shops#login", as: :login
  post "shops/logout", to: "shops#logout", as: :logout
  get "assign_cards", to: "cards#before_assign", as: :before_assign_cards
  post "assign_cards_do", to: "cards#assign", as: :assign_cards
  get "checkout", to: "pages#checkout", as: :checkout
  get "SDT", to: "pages#checkout_sdt", as: :checkout_sdt
  post "users/get_by_card", to: "users#get_by_card", as: :get_user_by_card
  post "save_checkout", to: "orders#save_checkout", as: :save_checkout
  post "save_checkout-sdt", to: "orders#save_checkout_sdt", as: :save_checkout_sdt
  get "saloon", to: "pages#saloon", as: :saloon
  get "shops/:id/specials", to: "shops#view_specials", as: :view_specials
  post "shops/:id/specials/add/:special_id", to: "shops#add_special"
  post "shops/:id/specials/remove/:special_id", to: "shops#remove_special"
  get "specials/:id/shops", to: "specials#view_shops", as: :view_shops_for_special
  post "specials/:id/shops/add/:shop_id", to: "specials#add_shop"
  post "specials/:id/shops/remove/:shop_id", to: "specials#remove_shop"
  get "read_cards", to: "cards#before_read", as: :before_read_cards
  post "read_cards_do", to: "cards#read", as: :read_cards
  post "cancel_order", to: "orders#cancel_order", as: :cancel_order
  post "transfer", to: "cards#transfer", as: :transfer
  post "save_saloon", to: "orders#save_saloon", as: :save_saloon
  get "stats", to: "pages#stats", as: :stats
  get "gripss", to: "pages#simple_stats", as: :simple_stats
  get "socks_dashboard", to: "stocks#dashboard", as: :stocks_dashboard
  post "add_stock", to: "stocks#add_stock", as: :add_stock
  get "handlewsold/:channel", to: "messages#handle"
  get "handlews/:channel/:shop", to: "messages#handle_redis"
  get "chatter", to: "messages#chatter", as: :chatter
  get "JOUJOUxxx111", to: "shops#quick_start"

  root 'pages#home'

  

end

app/models/card.rb
#encoding: utf-8
class Card < ActiveRecord::Base
  belongs_to :scannable, polymorphic: true
end

app/controllers/cards_controller.rb
#encoding: utf-8
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]
  skip_before_action :check_su, only: [:read, :transfer]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.includes(:scannable).to_a
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render action: 'show', status: :created, location: @card }
      else
        format.html { render action: 'new' }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url }
      format.json { head :no_content }
    end
  end

  def before_assign
    @products = Product.includes(:cards).to_a
    @specials = Special.includes(:cards).to_a
  end

  def assign
    if params[:scannable_id].blank? || params[:scannable_type].blank? || params[:uid].blank?
      render json: {status: 'error', message: "try harder"}
    else 
      card = Card.includes(:scannable).find_by uid: params[:uid]
      if card
        render json: {status: 'success', card: card.scannable.name}
      else
        card = Card.new()
        card.with_lock do
          if params[:scannable_type] != "User"
            card.scannable_type = params[:scannable_type]
            card.scannable_id = params[:scannable_id]
            card.uid = params[:uid]
          else
            user = User.new(amount: 0.00)
            user.with_lock do
              if user.save!
                card = Card.new(scannable_type: params[:scannable_type], scannable_id: user.id, uid: params[:uid])
              else
                render json: {status: 'error', message: "DB error while user save"}
              end
            end
          end
          if card.save!
            render json: {status: 'success', scannable: card.scannable.name}
          else
            render json: {status: 'error', message: "DB error while card save"}
          end
        end
      end
    end
  end

  def before_read
  end

  def read
    if params[:uid].blank?
      render json: {status: 'error', message: "try harder"}
    else
      card = Card.includes(:scannable).find_by uid: params[:uid]
      if card
        render json: {status: 'success', name: card.scannable.name}
      else
        render json: {status: 'error'}
      end
    end
  end

  def transfer
    if params[:uid1].blank? || params[:uid2].blank?
      render json: {status: 'error', message: "try harder"}
    else
      card1 = Card.includes(:scannable).find_by uid: params[:uid1]
      card2 = Card.includes(:scannable).find_by uid: params[:uid2]
      if card1 && card1.scannable_type = "User"
        user1 = card1.scannable
        if card2 && card1.scannable_type = "User"
          user2 = card2.scannable
          if user2.update_attribute(:amount, user1.amount + user2.amount) && user1.update_attribute(:amount, 0)
            render json: {status: 'success', amount: user2.amount}
          else
            render json: {status: 'error', message: "La transaction a échouée"}
          end
        else
          render json: {status: 'error', message: "Deuxième client introuvable"}
        end
      else
        render json: {status: 'error', message: "Premier client introuvable"}
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:scannable_id, :scannable_type, :uid)
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :scannable_id %><br>
    <%= f.number_field :scannable_id %>
  </div>
  <div class="field">
    <%= f.label :scannable_type %><br>
    <%= f.text_field :scannable_type %>
  </div>
  <div class="field">
    <%= f.label :uid %><br>
    <%= f.text_field :uid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cards/before_assign.html.erb
<div class="container text-center">
	<br>
	<h1>Assignation des cartes</h1>
	<br>
	<div class="assign-form">
		
	    <div class="form-group">
	    	<select id="type" class="assign-select">
		    	<option value="User">Client</option>
		    	<option value="Product">Produit</option>
		    	<option value="Special">Action</option>
		    </select>
	    </div>

	    <div class="form-group">
			<div>
	    		<select id="products" class="assign-select">
	    			<% @products.each do |p| %>
	    				<option value="<%= p.id %>"><%= p.name %></option>
	    			<% end %>
				</select>	
	    		<select id="specials" class="assign-select">
	    			<% @specials.each do |s| %>
	    				<option value="<%= s.id %>"><%= s.name %></option>
	    			<% end %>
				</select>	
			</div>
	    </div>

		<div class="form-group">
			<input type="text" class="form-control assign-input" id="scan" placeholder="En attente d'un scan" autocomplete="off">
		</div>

		<p class="lead" data-bind="html: infopg, style: { color: colorpg() < 0 ? '#3498db' : '#2ecc71' }"></p>
	</div>
</div>

<script>
	$("#scan").focus();
	$("#type").val("User");
	$("#products").hide();
	$("#specials").hide();
	$('#scan').keyup(function(e){
	    if (e.keyCode == 13) {
	        $(this).trigger("enterKey");
	    };
	});

	$('#type').change(function(){
		if (this.value=="Product") {
			$('#products').show();
			$('#specials').hide();
		} else if (this.value=="User") {
			$('#products').hide();
			$('#specials').hide();
		} else if (this.value=="Special") {
			$('#products').hide();
			$('#specials').show();
		};
	});

	var AssignViewModel = function() {
		var self = this;
		self.infopg = ko.observable("");
		self.colorpg = ko.observable(111);

		$('#scan').bind("enterKey",function(e){
			var uid = this.value;
			if ($('#type').val()=="Product") {
				var scannable_id = $('#products').val();
			} else if ($('#type').val()=="Special"){
				var scannable_id = $('#specials').val();
			} else {
				var scannable_id = 0;
			};
			self.infopg("...");
			json_data = {scannable_type: $('#type').val(), scannable_id: scannable_id, uid: uid};
			$.post("<%= url_for(assign_cards_path) %>", json_data, function(server_data) {
	            if (server_data.status == "success") {
	            	if (typeof server_data.card != 'undefined') {
	            		self.colorpg(-111);
	            		self.infopg('Déjà assignée :<br>'+server_data.card);
	            	} else {
	            		self.colorpg(111);
	            		self.infopg('Assignation réussie !<br>'+server_data.scannable+'<br>Carte #'+uid);
	            	};
	            } else {
	            	alert('Quelque chose s\'est mal passé, réessaye !');
	            };
	        }).error(function() {
	            alert('erreur lors du post AJAX! Recharge la page avant de continuer.')
	        });
			this.value=null;
		});
	};

	ko.applyBindings(new AssignViewModel());

</script>

app/views/cards/before_read.html.erb
<div class="container text-center">
	<br>
	<h1>Lecture des cartes</h1>
	<br>
		<div class="assign-form">
			
			<div class="form-group">
				<input type="text" class="form-control assign-input" id="scan" placeholder="En attente d'un scan" autocomplete="off">
			</div>

			<p class="lead" data-bind="html: infopg, style: { color: colorpg() < 0 ? '#e74c3c' : '#2ecc71' }"></p>
		</div>
</div>

<script>
	$("#scan").focus();
	$('#scan').keyup(function(e){
	    if (e.keyCode == 13) {
	        $(this).trigger("enterKey");
	    };
	});

	var ReadViewModel = function() {
		var self = this;
		self.infopg = ko.observable("");
		self.colorpg = ko.observable(111);

		$('#scan').bind("enterKey",function(e){
			var uid = this.value;
			self.infopg("...");
			$.post("<%= url_for(read_cards_path) %>", {uid: uid}, function(server_data) {
	            if (server_data.status == "success") {
            		self.colorpg(111);
            		self.infopg('Carte #' + uid + '<br>'+server_data.name);
	            } else {
            		self.colorpg(-111);
            		self.infopg('carte inconnue');
	            };
	        }).error(function() {
	            alert('erreur lors du post AJAX! Recharge la page avant de continuer.');
	        });
			this.value=null;
		});
	};

	ko.applyBindings(new ReadViewModel());

</script>

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<div class="container">

<h1>Listing cards</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Uid</th>
      <th>Scannable</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.uid %></td>
        <td><%= card.scannable.name %></td>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_card_path %>
</div>

app/views/cards/new.html.erb
<h1>New card</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Scannable:</strong>
  <%= @card.scannable_id %>
</p>

<p>
  <strong>Scannable type:</strong>
  <%= @card.scannable_type %>
</p>

<p>
  <strong>Uid:</strong>
  <%= @card.uid %>
</p>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>