config/routes.rb
Zscan::Application.routes.draw do

  resources :stocks

  resources :specials

  resources :orders

  resources :users

  resources :cards

  resources :products

  resources :shops

  get "pages/home"
  get "pages/admin_panel"
  get "shops/:id/products", to: "shops#view_products", as: :view_products
  post "shops/:id/products/add/:product_id", to: "shops#add_product"
  post "shops/:id/products/remove/:product_id", to: "shops#remove_product"
  get "products/:id/shops", to: "products#view_shops", as: :view_shops_for_product
  post "products/:id/shops/add/:shop_id", to: "products#add_shop"
  post "products/:id/shops/remove/:shop_id", to: "products#remove_shop"
  get "login", to: "shops#before_login", as: :before_login
  post "shops/login", to: "shops#login", as: :login
  post "shops/logout", to: "shops#logout", as: :logout
  get "assign_cards", to: "cards#before_assign", as: :before_assign_cards
  post "assign_cards_do", to: "cards#assign", as: :assign_cards
  get "checkout", to: "pages#checkout", as: :checkout
  get "SDT", to: "pages#checkout_sdt", as: :checkout_sdt
  post "users/get_by_card", to: "users#get_by_card", as: :get_user_by_card
  post "save_checkout", to: "orders#save_checkout", as: :save_checkout
  post "save_checkout-sdt", to: "orders#save_checkout_sdt", as: :save_checkout_sdt
  get "saloon", to: "pages#saloon", as: :saloon
  get "shops/:id/specials", to: "shops#view_specials", as: :view_specials
  post "shops/:id/specials/add/:special_id", to: "shops#add_special"
  post "shops/:id/specials/remove/:special_id", to: "shops#remove_special"
  get "specials/:id/shops", to: "specials#view_shops", as: :view_shops_for_special
  post "specials/:id/shops/add/:shop_id", to: "specials#add_shop"
  post "specials/:id/shops/remove/:shop_id", to: "specials#remove_shop"
  get "read_cards", to: "cards#before_read", as: :before_read_cards
  post "read_cards_do", to: "cards#read", as: :read_cards
  post "cancel_order", to: "orders#cancel_order", as: :cancel_order
  post "transfer", to: "cards#transfer", as: :transfer
  post "save_saloon", to: "orders#save_saloon", as: :save_saloon
  get "stats", to: "pages#stats", as: :stats
  get "gripss", to: "pages#simple_stats", as: :simple_stats
  get "socks_dashboard", to: "stocks#dashboard", as: :stocks_dashboard
  post "add_stock", to: "stocks#add_stock", as: :add_stock
  get "handlewsold/:channel", to: "messages#handle"
  get "handlews/:channel/:shop", to: "messages#handle_redis"
  get "chatter", to: "messages#chatter", as: :chatter
  get "JOUJOUxxx111", to: "shops#quick_start"

  root 'pages#home'

  

end

app/models/product.rb
#encoding: utf-8
class Product < ActiveRecord::Base
  has_and_belongs_to_many :shops
  has_and_belongs_to_many :orders
  has_many :stocks
  has_many :cards, as: :scannable, dependent: :destroy
  has_many :children, class_name: "Product", foreign_key: "parent_id"
  belongs_to :parent, class_name: "Product"

  validates_presence_of :name, message: "Le nom ne doit pas rester vide."
  validates_presence_of :price, message: "Le prix ne doit pas rester vide."
  validates_uniqueness_of :name, message: "Ce nom est deja pris."
  validates_numericality_of :price, message: "Prix incorrect."
end

app/controllers/products_controller.rb
#encoding: utf-8
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :view_shops, :add_shop, :remove_shop]
  before_action :set_shop, only: [:add_shop, :remove_shop]


  # GET /products
  # GET /products.json
  def index
    @products = Product.includes(:shops, :cards).to_a
    @products.sort! { |a,b| a.name <=> b.name }

  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_url, success: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to products_url, success: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  def view_shops
    @shops = Shop.order(name: :asc).to_a

    respond_to do |format|
      format.html # view_products.html.erb
      format.json { render json: @product }
    end
  end

  def add_shop
    if @product.shops << @shop
      render json: {status: "success"}
    else
      render json: {status: "error"}
    end
  end

  def remove_shop
    if @product.shops.delete(@shop)
      render json: {status: "success"}
    else
      render json: {status: "error"}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    def set_shop
      @shop = Shop.find(params[:shop_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :parent_id, :parent_qty)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="container">
  
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br>
    <%= collection_select(:product, :parent_id, Product.order(name: :asc).all, :id, :name, include_blank: "Pas de parent") %>
  </div>
  <div class="field">
    <%= f.label :parent_qty %><br>
    <%= f.text_field :parent_qty %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="container">
  
<p>Refaire les validation pour interdire les ' et "</p>
<h1>Produits du Gala</h1>
<%= link_to 'Nouveau produit', new_product_path %>
<br><br>
<table class='table table-hover'>
  <thead>
    <tr>
      <th>Nom</th>
      <th>Description</th>
      <th>Prix</th>
      <th>Appro</th> 
      <th>Cartes</th>
      <th>Pian'ss</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td>
          <%= if product.parent
                product.parent.name + " (" + product.parent_qty.to_s + "%)"
              else
                nil 
              end %>
        </td>
        <td><%= product.cards.length %></td>
        <td><%= link_to product.shops.length, view_shops_for_product_path(product) %></td>
        <td><%= link_to 'Stats', product %></td>
        <td><%= link_to 'Modifier', edit_product_path(product) %></td>
        <td><%= link_to 'Detruire', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/products/view_shops.html.erb
<div class="container">
    
    <h1>
        Points de vente proposants <%= @product.name %>
        <br><small><%= @product.description %></small>
    </h1><br>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-4">
            <h3>Le proposent <small data-bind='text: shopsProduct().length'></small></h3>

            <table data-bind='visible: shopsProduct().length > 0' class="table table-condensed">
                <tbody data-bind='foreach: shopsProduct'>
                    <tr>
                        <td width="90%">
                            <span data-bind='text: name'></span>
                            <div data-bind="attr: { id: id }" class='pull-right'>
                                <%= image_tag("preloader.gif", :width => 60) %>
                            </div>
                        </td>
                        <td>
                            <a href="#" data-bind="click: $root.removeShop" class="glyphicon glyphicon-arrow-right"></a>
                        </td>
                    </tr>
                </tbody>
            </table>

        </div>
    
        <div class='col-md-4'>

            <h3>Ne le proposent pas <small data-bind='text: shopsTous().length'></small></h3>
            <table data-bind='visible: shopsTous().length > 0' class="table table-condensed">
                <tbody data-bind='foreach: shopsTous'>
                    <tr>
                        <td width="90%">
                            <span data-bind='text: name'></span>
                            <div data-bind='attr: { id: id }' class='pull-right'>
                                <%= image_tag("preloader.gif", :width => 60) %>
                            </div>
                        </td>
                        <td>
                            <a href='#' data-bind='click: $root.addShop' class="glyphicon glyphicon-arrow-left"></a>
                        </td>
                    </tr>
                </tbody>
            </table>

        </div>
    </div>
</div>


</div>

<script>

function addReservation(id, name) {
    var self  = this;
    self.id   = id;
    self.name = name;
};

function ReservationsViewModel() {
    var self = this;


    self.shopsProduct = ko.observableArray([ <% @product.shops.each do |shop | %> <%= raw 'new addReservation(' + shop.id.to_s + ',"' + shop.name + '"),' %> <% end %>
    //new addReservation(id, name, price),
    ]);

    self.shopsTous = ko.observableArray([ <% @shops.each do |unshop | %> <%= raw 'new addReservation(' + unshop.id.to_s + ',"' + unshop.name + '"),' %> <% end %>
    //new addReservation(id, name, price),
    ]);


    self.Doublons = function() {

        for (var i = 0; i < self.shopsProduct().length; i++) {
            for (var j = 0; j < self.shopsTous().length; j++) {
                if (self.shopsProduct()[i].name == self.shopsTous()[j].name) {
                    self.shopsTous.remove(self.shopsTous()[j]);
                    break;
                };
            };
        };
    };
    self.Doublons();

    self.addShop = function(shopsTous) {

        $('#' + shopsTous.id).show();
        self.shopsTous.remove(shopsTous);
        self.shopsProduct.push(new addReservation(shopsTous.id, shopsTous.name, shopsTous.price));

        $.post('<%= view_shops_for_product_path(@product) + "/add/" %>' + shopsTous.id, {}, function(allData) {
            if (allData.status == "success") {
                $('#' + shopsTous.id).hide();
            } else {
                self.shopsProduct.remove(shopsTous);
                self.shopsTous.push(new addReservation(shopsTous.id, shopsTous.name, shopsTous.price));
            };

        }).error(function() {
            alert('erreur lors du post AJAX! Recharge la page avant de continuer.');
        });
    };

    self.removeShop = function(shopsProduct) {

        $('#' + shopsProduct.id).show();
        self.shopsProduct.remove(shopsProduct);
        self.shopsTous.push(new addReservation(shopsProduct.id, shopsProduct.name, shopsProduct.price));

        $.post('<%= view_shops_for_product_path(@product) + "/remove/" %>' + shopsProduct.id, {}, function(allData) {

            if (allData.status == "success") {
                $('#' + shopsProduct.id).hide();
            } else {
                self.shopsProduct.push(new addReservation(shopsProduct.id, shopsProduct.name, shopsProduct.price));
            };

        }).error(function() {
            alert('erreur lors du post AJAX! Recharge la page avant de continuer.');
        });
    };

};

ko.applyBindings(new ReservationsViewModel());

<% @shops.each do |unshop| %>
<%= raw "$('#" + unshop.id.to_s + "').hide();" %>
<% end %>

</script>