config/routes.rb
Zscan::Application.routes.draw do

  resources :stocks

  resources :specials

  resources :orders

  resources :users

  resources :cards

  resources :products

  resources :shops

  get "pages/home"
  get "pages/admin_panel"
  get "shops/:id/products", to: "shops#view_products", as: :view_products
  post "shops/:id/products/add/:product_id", to: "shops#add_product"
  post "shops/:id/products/remove/:product_id", to: "shops#remove_product"
  get "products/:id/shops", to: "products#view_shops", as: :view_shops_for_product
  post "products/:id/shops/add/:shop_id", to: "products#add_shop"
  post "products/:id/shops/remove/:shop_id", to: "products#remove_shop"
  get "login", to: "shops#before_login", as: :before_login
  post "shops/login", to: "shops#login", as: :login
  post "shops/logout", to: "shops#logout", as: :logout
  get "assign_cards", to: "cards#before_assign", as: :before_assign_cards
  post "assign_cards_do", to: "cards#assign", as: :assign_cards
  get "checkout", to: "pages#checkout", as: :checkout
  get "SDT", to: "pages#checkout_sdt", as: :checkout_sdt
  post "users/get_by_card", to: "users#get_by_card", as: :get_user_by_card
  post "save_checkout", to: "orders#save_checkout", as: :save_checkout
  post "save_checkout-sdt", to: "orders#save_checkout_sdt", as: :save_checkout_sdt
  get "saloon", to: "pages#saloon", as: :saloon
  get "shops/:id/specials", to: "shops#view_specials", as: :view_specials
  post "shops/:id/specials/add/:special_id", to: "shops#add_special"
  post "shops/:id/specials/remove/:special_id", to: "shops#remove_special"
  get "specials/:id/shops", to: "specials#view_shops", as: :view_shops_for_special
  post "specials/:id/shops/add/:shop_id", to: "specials#add_shop"
  post "specials/:id/shops/remove/:shop_id", to: "specials#remove_shop"
  get "read_cards", to: "cards#before_read", as: :before_read_cards
  post "read_cards_do", to: "cards#read", as: :read_cards
  post "cancel_order", to: "orders#cancel_order", as: :cancel_order
  post "transfer", to: "cards#transfer", as: :transfer
  post "save_saloon", to: "orders#save_saloon", as: :save_saloon
  get "stats", to: "pages#stats", as: :stats
  get "gripss", to: "pages#simple_stats", as: :simple_stats
  get "socks_dashboard", to: "stocks#dashboard", as: :stocks_dashboard
  post "add_stock", to: "stocks#add_stock", as: :add_stock
  get "handlewsold/:channel", to: "messages#handle"
  get "handlews/:channel/:shop", to: "messages#handle_redis"
  get "chatter", to: "messages#chatter", as: :chatter
  get "JOUJOUxxx111", to: "shops#quick_start"

  root 'pages#home'

  

end

app/views/layouts/_flash_messages.html.erb
<div class="container">
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %> fade-in alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= value %>
    </div>
  <% end %>
</div>
<script>
	$( document ).ready(function() {
console.log( "ready!" );
$( ".alert-dismissable" ).delay( 2000 ).slideUp(700);

});


</script>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse" role="navigation" id="navbar">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <li class='dropdown navbar-brand'>
        <span class="dropdown-toggle INESS-brand" data-toggle="dropdown">
          INESS
        </span>
        <ul class="dropdown-menu">
          <% if session[:shop_level] == 1 || session[:shop_level] == 10 %>
            <li>
              <%= link_to saloon_path do %>
                <span class="glyphicon glyphicon-fire"></span> Bar
              <% end %>
            </li>
          <% end %>
          <% if session[:shop_level] == 2 || session[:shop_level] == 10 %>
            <li>
              <%= link_to checkout_path do %>
                <span class="glyphicon glyphicon-fire"></span> Caisse
              <% end %>
            </li>
          <% end %>
          <% if session[:shop_level] == 3 || session[:shop_level] == 10 %>
            <li>
              <%= link_to checkout_sdt_path do %>
                <span class="glyphicon glyphicon-fire"></span> Caisse SDT
              <% end %>
            </li>
          <% end %>
          <% if session[:shop_level] == 4 || session[:shop_level] == 10 %>
            <li>
              <%= link_to stocks_dashboard_path do %>
                <span class="glyphicon glyphicon-shopping-cart"></span> Appros
              <% end %>
            </li>
          <% end %>
          <% if session[:shop_level] == 6 || session[:shop_level] == 10 %>
            <li>
              <%= link_to chatter_path do %>
                <span class="glyphicon glyphicon-bullhorn"></span> Chatter
              <% end %>
            </li>
          <% end %>
          <% if session[:shop_level] == 10 %>
            <li>
              <%= link_to stats_path do %>
                <span class="glyphicon glyphicon-stats"></span> Statistiques
              <% end %>
            </li>
          <% end %>
          <% if session[:shop_level] == 5 || session[:shop_level] == 10 %>
            <li>
              <%= link_to simple_stats_path do %>
                <span class="glyphicon glyphicon-stats"></span> Grip'sserie
              <% end %>
            </li>
          <% end %>
          <li>
            <%= link_to root_path do %>
              <span class="glyphicon glyphicon-home"></span> Accueil
            <% end %>
          </li>
        </ul>
      </li>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <!-- <li class="active"><a href="#">Link</a></li> -->
      <% if session[:shop_level] == 10 %>
        <li>
          <%= link_to shops_path do %>
            <span class="glyphicon glyphicon-map-marker"></span> Pian'ss
          <% end %>
        </li>
        <li>
          <%= link_to users_path do %>
            <span class="glyphicon glyphicon-user"></span> Clients
          <% end %>
        </li>
        <li>
          <%= link_to products_path do %>
            <span class="glyphicon glyphicon-glass"></span> Produits
          <% end %>
        </li>
        <li>
          <%= link_to specials_path do %>
            <span class="glyphicon glyphicon-star"></span> Actions
          <% end %>
        </li>
        <li>
          <%= link_to orders_path do %>
            <span class="glyphicon glyphicon-list-alt"></span> Commandes
          <% end %>
        </li>
        <li class='dropdown'>
          <a href="" class="dropdown-toggle" data-toggle="dropdown">
            <span class="glyphicon glyphicon-credit-card"></span> Cartes
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Liste', cards_path %></li>
            <li><%= link_to 'Lire', before_read_cards_path %></li>
            <li><%= link_to 'Assigner', before_assign_cards_path %></li>
          </ul>
        </li>
      <% end %>
    </ul> 
    <ul class="nav navbar-nav navbar-right">
      <li>
        <a class="clock">00h00</a>
      </li>
      <li>
        <% if session[:shop_id] %>
          <%= link_to logout_path, method: :post do %>
            <%= session[:shop_name] %> <i class="glyphicon glyphicon-off"></i>
          <% end %>
        <% else %>
          <%= link_to before_login_path do %>
            <i class="glyphicon glyphicon-off"></i>
          <% end %>
        <% end %>
      </li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>
<div id="post-navbar"></div>

<script>
  function refreshTime () {
    // body...
    var d = new Date();
    var h = d.getHours().toString();
    var m = d.getMinutes().toString();
    if (h.length < 2) {  h = "0" + h};
    if (m.length < 2) {  m = "0" + m};
    $('.clock').html(h+"h"+m);
  }
  refreshTime();
  var whattimeisit = setInterval(refreshTime, 1000*10);

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>INESS</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/flash_messages' %>
    <%= yield %>
    <br>
  </body>

  <footer>
        <span class="pull-right text-muted small">@INESSproject</span>
  </footer>

</html>